# Dependabot will run on day 26 of each month at 01:11 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "11 1 26 * *"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/src-admin"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "11 1 26 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
